# ArgoCD Project definition
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: swiggy-gitops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Swiggy GitOps Project
  sourceRepos:
    - "https://github.com/<your-org>/swiggy-gitops.git"  # Replace with your repo
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"

  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true
